### ISSUE TITLE
Quest 2 melonloader (lemonloader) crash 

### ISSUE THREAD

**Issue by chandlju420** [extraes/JeviLib#1]
Looking at my melon loader log I finally discovered why bonelib won't load 80 percent of the time. It says jeviLib is missing dependencies and may not be loaded specifically it says this..

[01:15:44.260] [WARNING] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'JeviLib' is missing the following dependencies:
    - 'Facepunch.Steamworks.Win64' v1.0.0.0

I've attached the latest log for you. Please fix this I love the quicksilver mod but it requires thus which this causes it and the while bonemenu to not load almost 80 percent of the time. I get lucky if it does load and if the game crashes I spend another hour trying to get it to load. I appreciate the hard work thou.

**Comment by extraes** [comment]
This warning does not crash the game or cause any issues.
Your crash is unrelated to JeviLib.
